package gq.codephon.digi_applimobs.items;

import gq.codephon.digi_applimobs.AppliUtils;
import gq.codephon.digi_applimobs.blocks.BlockReg;
import gq.codephon.digi_applimobs.group.ModGroup;
import gq.codephon.digi_applimobs.items.armors.*;
import gq.codephon.digi_applimobs.items.tools.*;
import gq.codephon.digi_applimobs.liq.FluidReg;
import net.minecraft.item.BlockItem;
import net.minecraft.item.BucketItem;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import static net.minecraft.item.Items.BUCKET;

public class ItemRegistry {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, AppliUtils.MOD_ID);
    public static final RegistryObject<Item> appliIngot = ITEMS.register("appli_ingot", AppliNormalItem::new);

    public static final RegistryObject<Item> appliIngotNugget = ITEMS.register("appli_nugget", AppliNormalItem::new);

    public static final RegistryObject<Item> appliStick = ITEMS.register("appli_stick", AppliNormalItem::new);
    public static final RegistryObject<Item> gatch_monaka = ITEMS.register("gatch_monaka", Gatch_Monaka::new);
    public static final RegistryObject<Item> appliSword = ITEMS.register("appli_sword", AppliSword::new);
    public static final RegistryObject<Item> appliPickaxe = ITEMS.register("appli_pickaxe", AppliPickaxe::new);
    public static final RegistryObject<Item> appliAxe = ITEMS.register("appli_axe", AppliAxe::new);
    public static final RegistryObject<Item> appliShovel = ITEMS.register("appli_shovel", AppliShovel::new);
    public static final RegistryObject<Item> appliHelmet = ITEMS.register("appli_helmet", AppliHelmet::new);
    public static final RegistryObject<Item> appliChestPlate = ITEMS.register("appli_chestplate", AppliChestplate::new);
    public static final RegistryObject<Item> appliLeggings = ITEMS.register("appli_leggings", AppliLeggings::new);
    public static final RegistryObject<Item> appliBoots = ITEMS.register("appli_boots", AppliBoots::new);
    public static final RegistryObject<Item> fuminbHelmet = ITEMS.register("fuminb_helmet", FuminbHel::new);
    public static final RegistryObject<Item> applibow = ITEMS.register("appli_bow", AppliBow::new);

    public static final RegistryObject<Item> appliDrive = ITEMS.register("appli_drive", AppliDrive::new);
    public static final RegistryObject<Item> appliDriveDUO = ITEMS.register("appli_drive_duo", AppliDriveDUO::new);

    public static final RegistryObject<Item> NetFluidBucket = ITEMS.register("net_liq_bucket", () -> new BucketItem(FluidReg.netWater, new Item.Properties().tab(ModGroup.itemGroup).craftRemainder(BUCKET)));

    public static final RegistryObject<Item> appliBlock =
            ITEMS.register("appli_block",
                    ()->new BlockItem(BlockReg.appliBlock.get(), new Item.Properties().tab(ModGroup.itemGroup)));
    public static final RegistryObject<Item> appliOre =
            ITEMS.register("appli_ore",
                    ()->new BlockItem(BlockReg.appliOre.get(), new Item.Properties().tab(ModGroup.itemGroup)));

    public static final RegistryObject<Item> appliFloor =
            ITEMS.register("appli_floor",
                    ()->new BlockItem(BlockReg.appliFloor.get(), new Item.Properties().tab(ModGroup.itemGroup)));

    public static final RegistryObject<Item> appliChipGatchmob = ITEMS.register("applichip_gatchmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCallmob = ITEMS.register("applichip_callmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMailmob = ITEMS.register("applichip_mailmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTubumob = ITEMS.register("applichip_tubumob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGengomob = ITEMS.register("applichip_gengomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipAddmob = ITEMS.register("applichip_addmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipReviewmob = ITEMS.register("applichip_reviewmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSetmob = ITEMS.register("applichip_setmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMessemob = ITEMS.register("applichip_messemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGugumob = ITEMS.register("applichip_gugumob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipKosomob = ITEMS.register("applichip_kosomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDogatchmob = ITEMS.register("applichip_dogatchmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSociamob = ITEMS.register("applichip_sociamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGossipmob = ITEMS.register("applichip_gossipmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSukasimob = ITEMS.register("applichip_sukasimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipLogimob = ITEMS.register("applichip_logimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipLogamob = ITEMS.register("applichip_logamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGlobemob = ITEMS.register("applichip_globemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCharismob = ITEMS.register("applichip_charismob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDamedamob = ITEMS.register("applichip_damedamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRocketmob = ITEMS.register("applichip_rocketmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipNavimob = ITEMS.register("applichip_navimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipJetmob = ITEMS.register("applichip_jetmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipWeathermob = ITEMS.register("applichip_weathermob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCompassmob = ITEMS.register("applichip_compassmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipYadomob = ITEMS.register("applichip_yadomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipNewsmob = ITEMS.register("applichip_newsmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTutomob = ITEMS.register("applichip_tutomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMcmob = ITEMS.register("applichip_mcmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipResshamob = ITEMS.register("applichip_resshamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSpeciamob = ITEMS.register("applichip_speciamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTripmob = ITEMS.register("applichip_tripmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipWeatherdramob = ITEMS.register("applichip_weatherdramob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSateramob = ITEMS.register("applichip_sateramob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCometmob = ITEMS.register("applichip_cometmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipProtecmob = ITEMS.register("applichip_protecmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipHackmob = ITEMS.register("applichip_hackmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipBatterimob = ITEMS.register("applichip_batterimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipPekomob = ITEMS.register("applichip_pekomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipPokomob = ITEMS.register("applichip_pokomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCopipemob = ITEMS.register("applichip_copipemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSavemob = ITEMS.register("applichip_savemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipKabemob = ITEMS.register("applichip_kabemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipEcomob = ITEMS.register("applichip_ecomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipPipomob = ITEMS.register("applichip_pipomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRaidramob = ITEMS.register("applichip_raidramob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDezipmob = ITEMS.register("applichip_dezipmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMienumob = ITEMS.register("applichip_mienumob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipWarpmob = ITEMS.register("applichip_warpmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDenpamob = ITEMS.register("applichip_denpamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSupermob = ITEMS.register("applichip_supermob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRevivemob = ITEMS.register("applichip_revivemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipWarudamob = ITEMS.register("applichip_warudamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDrawmob = ITEMS.register("applichip_drawmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTellermob = ITEMS.register("applichip_tellermob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMusimob = ITEMS.register("applichip_musimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipPerorimob = ITEMS.register("applichip_perorimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDressmob = ITEMS.register("applichip_dressmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipBookmob = ITEMS.register("applichip_bookmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGashamob = ITEMS.register("applichip_gashamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipLuckmob = ITEMS.register("applichip_luckmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTrickmob = ITEMS.register("applichip_trickmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDicemob = ITEMS.register("applichip_dicemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCookmob = ITEMS.register("applichip_cookmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDogamob = ITEMS.register("applichip_dogamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipEffecmob = ITEMS.register("applichip_effecmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipJumpplusmob = ITEMS.register("applichip_jumpplusmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTarotmob = ITEMS.register("applichip_tarotmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCoordemob = ITEMS.register("applichip_coordemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMediamob = ITEMS.register("applichip_mediamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipVegasmob = ITEMS.register("applichip_vegasmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDreamob = ITEMS.register("applichip_dreammob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSantamob = ITEMS.register("applichip_santamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipEntermob = ITEMS.register("applichip_entermob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSleepmob = ITEMS.register("applichip_sleepmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMusclemob = ITEMS.register("applichip_musclemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipAidmob = ITEMS.register("applichip_aidmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMoneymob = ITEMS.register("applichip_moneymob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSpamob = ITEMS.register("applichip_spamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSupplemob = ITEMS.register("applichip_supplemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDopemob = ITEMS.register("applichip_dopemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipAuctiomob = ITEMS.register("applichip_auctiomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipKakeimob = ITEMS.register("applichip_kakeimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipKaimob = ITEMS.register("applichip_kaimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipJishomob = ITEMS.register("applichip_jishomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipVirusmob = ITEMS.register("applichip_virusmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMedicmob = ITEMS.register("applichip_medicmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDocmob = ITEMS.register("applichip_docmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipConsulmob = ITEMS.register("applichip_consulmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipLibramob = ITEMS.register("applichip_libramob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipBiomob = ITEMS.register("applichip_biomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipBeautymob = ITEMS.register("applichip_beautymob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCameramob = ITEMS.register("applichip_cameramob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRecomob = ITEMS.register("applichip_recomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCalcumob = ITEMS.register("applichip_calcumob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGomimob = ITEMS.register("applichip_gomimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipMirrormob = ITEMS.register("applichip_mirrormob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipLightmob = ITEMS.register("applichip_lightmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipWatchmob = ITEMS.register("applichip_watchmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDiarimob = ITEMS.register("applichip_diarimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCalendamob = ITEMS.register("applichip_calendamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipOnpamob = ITEMS.register("applichip_onpamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipJammingmob = ITEMS.register("applichip_jammingmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTimemob = ITEMS.register("applichip_timemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRoamob = ITEMS.register("applichip_roamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipScorpmob = ITEMS.register("applichip_scorpmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCraftmob = ITEMS.register("applichip_craftmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipFakemob = ITEMS.register("applichip_fakemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipBootmob = ITEMS.register("applichip_bootmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipShutmob = ITEMS.register("applichip_shutmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDokamob = ITEMS.register("applichip_dokamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipShotmob = ITEMS.register("applichip_shotmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCardmob = ITEMS.register("applichip_cardmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRopuremob = ITEMS.register("applichip_ropuremob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipPuzzlemob = ITEMS.register("applichip_puzzlemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDancemob = ITEMS.register("applichip_dancemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRacemob = ITEMS.register("applichip_racemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipOnmob = ITEMS.register("applichip_onmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipOffmob = ITEMS.register("applichip_offmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipV_jumpmob = ITEMS.register("applichip_vjumpmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDosukomob = ITEMS.register("applichip_dosukomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipBramob = ITEMS.register("applichip_bramob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipCoachmob = ITEMS.register("applichip_coachmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipGaiamob = ITEMS.register("applichip_gaiamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipOujamob = ITEMS.register("applichip_oujamob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSakusimob = ITEMS.register("applichip_sakusimob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipUratekumob = ITEMS.register("applichip_uratekumob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipHadesmob = ITEMS.register("applichip_hadesmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipPoseidomob = ITEMS.register("applichip_poseidomob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipRebootmob = ITEMS.register("applichip_rebootmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDeusumob = ITEMS.register("applichip_deusumob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipOuranosmob = ITEMS.register("applichip_ouranosmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipDantemob = ITEMS.register("applichip_dantemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipFlickmob = ITEMS.register("applichip_flickmob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipSwipemob = ITEMS.register("applichip_swipemob",AppliChipItem::new);
    public static final RegistryObject<Item> appliChipTapmob = ITEMS.register("applichip_tapmob",AppliChipItem::new);


    public static final RegistryObject<Item> appliUnlockedChipGatchmob = ITEMS.register("applichip_gatchmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCallmob = ITEMS.register("applichip_callmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMailmob = ITEMS.register("applichip_mailmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTubumob = ITEMS.register("applichip_tubumob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGengomob = ITEMS.register("applichip_gengomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipAddmob = ITEMS.register("applichip_addmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipReviewmob = ITEMS.register("applichip_reviewmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSetmob = ITEMS.register("applichip_setmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMessemob = ITEMS.register("applichip_messemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGugumob = ITEMS.register("applichip_gugumob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipKosomob = ITEMS.register("applichip_kosomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDogatchmob = ITEMS.register("applichip_dogatchmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSociamob = ITEMS.register("applichip_sociamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGossipmob = ITEMS.register("applichip_gossipmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSukasimob = ITEMS.register("applichip_sukasimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipLogimob = ITEMS.register("applichip_logimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipLogamob = ITEMS.register("applichip_logamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGlobemob = ITEMS.register("applichip_globemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCharismob = ITEMS.register("applichip_charismob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDamedamob = ITEMS.register("applichip_damedamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRocketmob = ITEMS.register("applichip_rocketmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipNavimob = ITEMS.register("applichip_navimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipJetmob = ITEMS.register("applichip_jetmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipWeathermob = ITEMS.register("applichip_weathermob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCompassmob = ITEMS.register("applichip_compassmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipYadomob = ITEMS.register("applichip_yadomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipNewsmob = ITEMS.register("applichip_newsmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTutomob = ITEMS.register("applichip_tutomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMcmob = ITEMS.register("applichip_mcmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipResshamob = ITEMS.register("applichip_resshamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSpeciamob = ITEMS.register("applichip_speciamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTripmob = ITEMS.register("applichip_tripmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipWeatherdramob = ITEMS.register("applichip_weatherdramob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSateramob = ITEMS.register("applichip_sateramob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCometmob = ITEMS.register("applichip_cometmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipProtecmob = ITEMS.register("applichip_protecmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipHackmob = ITEMS.register("applichip_hackmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipBatterimob = ITEMS.register("applichip_batterimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipPekomob = ITEMS.register("applichip_pekomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipPokomob = ITEMS.register("applichip_pokomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCopipemob = ITEMS.register("applichip_copipemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSavemob = ITEMS.register("applichip_savemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipKabemob = ITEMS.register("applichip_kabemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipEcomob = ITEMS.register("applichip_ecomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipPipomob = ITEMS.register("applichip_pipomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRaidramob = ITEMS.register("applichip_raidramob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDezipmob = ITEMS.register("applichip_dezipmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMienumob = ITEMS.register("applichip_mienumob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipWarpmob = ITEMS.register("applichip_warpmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDenpamob = ITEMS.register("applichip_denpamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSupermob = ITEMS.register("applichip_supermob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRevivemob = ITEMS.register("applichip_revivemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipWarudamob = ITEMS.register("applichip_warudamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDrawmob = ITEMS.register("applichip_drawmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTellermob = ITEMS.register("applichip_tellermob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMusimob = ITEMS.register("applichip_musimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipPerorimob = ITEMS.register("applichip_perorimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDressmob = ITEMS.register("applichip_dressmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipBookmob = ITEMS.register("applichip_bookmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGashamob = ITEMS.register("applichip_gashamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipLuckmob = ITEMS.register("applichip_luckmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTrickmob = ITEMS.register("applichip_trickmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDicemob = ITEMS.register("applichip_dicemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCookmob = ITEMS.register("applichip_cookmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDogamob = ITEMS.register("applichip_dogamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipEffecmob = ITEMS.register("applichip_effecmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipJumpplusmob = ITEMS.register("applichip_jumpplusmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTarotmob = ITEMS.register("applichip_tarotmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCoordemob = ITEMS.register("applichip_coordemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMediamob = ITEMS.register("applichip_mediamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipVegasmob = ITEMS.register("applichip_vegasmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDreamob = ITEMS.register("applichip_dreammob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSantamob = ITEMS.register("applichip_santamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipEntermob = ITEMS.register("applichip_entermob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSleepmob = ITEMS.register("applichip_sleepmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMusclemob = ITEMS.register("applichip_musclemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipAidmob = ITEMS.register("applichip_aidmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipmoneymob = ITEMS.register("applichip_moneymob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSpamob = ITEMS.register("applichip_spamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSupplemob = ITEMS.register("applichip_supplemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDopemob = ITEMS.register("applichip_dopemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipAuctiomob = ITEMS.register("applichip_auctiomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipKakeimob = ITEMS.register("applichip_kakeimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipKaimob = ITEMS.register("applichip_kaimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipJishomob = ITEMS.register("applichip_jishomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipVirusmob = ITEMS.register("applichip_virusmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMedicmob = ITEMS.register("applichip_medicmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDocmob = ITEMS.register("applichip_docmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipConsulmob = ITEMS.register("applichip_consulmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipLibramob = ITEMS.register("applichip_libramob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipBiomob = ITEMS.register("applichip_biomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipBeautymob = ITEMS.register("applichip_beautymob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCameramob = ITEMS.register("applichip_cameramob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRecomob = ITEMS.register("applichip_recomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCalcumob = ITEMS.register("applichip_calcumob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGomimob = ITEMS.register("applichip_gomimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipMirrormob = ITEMS.register("applichip_mirrormob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipLightmob = ITEMS.register("applichip_lightmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipWatchmob = ITEMS.register("applichip_watchmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDiarimob = ITEMS.register("applichip_diarimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCalendamob = ITEMS.register("applichip_calendamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipOnpamob = ITEMS.register("applichip_onpamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipJammingmob = ITEMS.register("applichip_jammingmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTimemob = ITEMS.register("applichip_timemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRoamob = ITEMS.register("applichip_roamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipScorpmob = ITEMS.register("applichip_scorpmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCraftmob = ITEMS.register("applichip_craftmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipFakemob = ITEMS.register("applichip_fakemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipBootmob = ITEMS.register("applichip_bootmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipShutmob = ITEMS.register("applichip_shutmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDokamob = ITEMS.register("applichip_dokamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipShotmob = ITEMS.register("applichip_shotmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCardmob = ITEMS.register("applichip_cardmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRopuremob = ITEMS.register("applichip_ropuremob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipPuzzlemob = ITEMS.register("applichip_puzzlemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDancemob = ITEMS.register("applichip_dancemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRacemob = ITEMS.register("applichip_racemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipOnmob = ITEMS.register("applichip_onmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipOffmob = ITEMS.register("applichip_offmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipV_jumpmob = ITEMS.register("applichip_vjumpmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDosukomob = ITEMS.register("applichip_dosukomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipBramob = ITEMS.register("applichip_bramob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipCoachmob = ITEMS.register("applichip_coachmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipGaiamob = ITEMS.register("applichip_gaiamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipOujamob = ITEMS.register("applichip_oujamob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSakusimob = ITEMS.register("applichip_sakusimob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipUratekumob = ITEMS.register("applichip_uratekumob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipHadesmob = ITEMS.register("applichip_hadesmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipPoseidomob = ITEMS.register("applichip_poseidomob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipRebootmob = ITEMS.register("applichip_rebootmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDeusumob = ITEMS.register("applichip_deusumob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipOuranosmob = ITEMS.register("applichip_ouranosmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipDantemob = ITEMS.register("applichip_dantemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipFlickmob = ITEMS.register("applichip_flickmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipSwipemob = ITEMS.register("applichip_swipemob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<Item> appliUnlockedChipTapmob = ITEMS.register("applichip_tapmob_unlocked",AppliUnlockedChipItem::new);
    public static final RegistryObject<AppmonBand> APPMONBAND = ITEMS.register( "appmon_band", AppmonBand::new);
}


